
// Número de ejemplo. Reemplazar por el WhatsApp comercial real, con código de país.
const WHATSAPP='51999999999';const products=[{name:'Fertilizante Foliar A',category:'Nutrición',description:'Solución de nutrición para programas de manejo agrícola.',tag:'Destacado',short:'NUTRI A'},{name:'Corrector de Suelo B',category:'Nutrición',description:'Producto demostrativo para la categoría de nutrición.',tag:'',short:'SUELO B'},{name:'Protector de Cultivo C',category:'Protección',description:'Ficha de ejemplo para el portafolio de protección.',tag:'Nuevo',short:'PROTECT C'},{name:'Bioestimulante D',category:'Bioestimulantes',description:'Solución de ejemplo para distintas etapas del cultivo.',tag:'',short:'BIO D'},{name:'Nutrición Integral E',category:'Nutrición',description:'Producto de referencia para exhibir especificaciones.',tag:'',short:'NUTRI E'},{name:'Protección Agrícola F',category:'Protección',description:'Producto de muestra para solicitar una cotización.',tag:'',short:'AGRO F'}];let category='Todos';const grid=document.querySelector('#grid');function link(msg){return 'https://wa.me/'+WHATSAPP+'?text='+encodeURIComponent(msg)}function render(){const query=document.querySelector('#search').value.trim().toLowerCase();let items=products.filter(p=>(category==='Todos'||category===p.category)&&p.name.toLowerCase().includes(query));grid.innerHTML=items.map(p=>`<article class="card"><div class="visual">${p.tag?`<span class="tag">${p.tag}</span>`:''}<div class="product-art"><div>${p.short}<small>AGRO SHESED</small></div></div></div><div class="card-body"><span class="category">${p.category}</span><h3>${p.name}</h3><p class="desc">${p.description}</p><div class="card-bottom"><span class="quote">Precio a cotizar</span><button class="consult" data-name="${p.name}">Solicitar cotización ↗</button></div></div></article>`).join('');document.querySelector('#empty').style.display=items.length?'none':'block'}document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()}));document.querySelector('#search').addEventListener('input',render);grid.addEventListener('click',e=>{let b=e.target.closest('.consult');if(b)window.open(link('Hola, quisiera una cotización de '+b.dataset.name+'.'),'_blank','noopener,noreferrer')});document.querySelector('#contactLink').href=link('Hola, quisiera asesoría sobre sus productos.');document.querySelector('#floating').href=link('Hola, quisiera asesoría sobre sus productos.');render();

// La pantalla de carga se retira después de que los recursos principales estén listos.
window.addEventListener('load',()=>{const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;window.setTimeout(()=>document.body.classList.add('site-ready'),reduce?0:1250)});


(function(){const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('.dot')];let index=0,timer;function show(n){index=(n+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.classList.toggle('active',i===index);slide.setAttribute('aria-hidden',String(i!==index));slide.querySelectorAll('a').forEach(a=>a.tabIndex=i===index?0:-1)});dots.forEach((dot,i)=>{dot.classList.toggle('active',i===index);if(i===index)dot.setAttribute('aria-current','true');else dot.removeAttribute('aria-current')})}function start(){clearInterval(timer);timer=setInterval(()=>show(index+1),6000)}document.querySelector('.slide-arrow.prev').onclick=()=>{show(index-1);start()};document.querySelector('.slide-arrow.next').onclick=()=>{show(index+1);start()};dots.forEach((dot,i)=>dot.onclick=()=>{show(i);start()});const slider=document.querySelector('.slider');slider.addEventListener('mouseenter',()=>clearInterval(timer));slider.addEventListener('mouseleave',start);slider.addEventListener('focusin',()=>clearInterval(timer));slider.addEventListener('focusout',e=>{if(!slider.contains(e.relatedTarget))start()});document.addEventListener('visibilitychange',()=>document.hidden?clearInterval(timer):start());show(0);if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)start()})();
